### ISSUE TITLE
Remove dbmigrate references

### ISSUE THREAD

**Issue by neokoenig** [chapmandu/Snippets#2]
https://github.com/chapmandu/Snippets/blob/0c1725e0a18eec25f9223412aa4d8c6a44bd1bb9/snippets.cfc#L182

Tried to get this running but dbmigrate needs updating to migrator, and after that, just including the Wheels striptag function etc doesn't seem to work.

**Comment by chapmandu** [comment]
Fixed via 9a6bca9
